// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------ //
// edge_counter //
// ------------ //

#define edge_counter_wrap_target 0
#define edge_counter_wrap 11

#define edge_counter_T1 4
#define edge_counter_T2 12

static const uint16_t edge_counter_program_instructions[] = {
	//     .wrap_target
0x80a0,
	//  0: pull   block                      
0xa047,
	//  1: mov    y, osr                     
0xa022,
	//  2: mov    x, y                       
0x20a0,
	//  3: wait   1 pin, 0                   
0x00c6,
	//  4: jmp    pin, 6                     
0x0002,
	//  5: jmp    2                          
0x0044,
	//  6: jmp    x--, 4                     
0x0008,
	//  7: jmp    8                          
0xe001,
	//  8: set    pins, 1                    
0xa542,
	//  9: nop                           [5] 
0xe000,
	// 10: set    pins, 0                    
0x0002,
	// 11: jmp    2                          
        //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program edge_counter_program = {
	.instructions = edge_counter_program_instructions,
	.length = 12,
	.origin = -1,
};

static inline pio_sm_config edge_counter_program_get_default_config(uint offset) {
	pio_sm_config c = pio_get_default_sm_config();
	sm_config_set_wrap(&c, offset + edge_counter_wrap_target, offset + edge_counter_wrap);
	return c;
}

#include "hardware/clocks.h"
#include "hardware/pio.h"
static inline void edge_counter_program_init(PIO pio, uint sm, uint offset)  
{
	pio_sm_config c = edge_counter_program_get_default_config(offset);
	sm_config_set_in_pins(&c, 3);
	sm_config_set_set_pins(&c, 28, 1);
	pio_sm_set_pindirs_with_mask(pio, sm, ~(1u << 3), 1u << 3 | 1u << 28);
	pio_gpio_init(pio, 3);
	pio_gpio_init(pio, 28);
	sm_config_set_in_shift(&c, false, false, 32);
	int cyclesPerBit = (edge_counter_T1 + edge_counter_T2) / 4;
	float frequency = 1000000;
	float clockDiv = clock_get_hz(clk_sys) / (cyclesPerBit * frequency);
	sm_config_set_clkdiv(&c, clockDiv);
	pio_sm_init(pio, sm, offset, &c);
	pio_sm_put_blocking(pio, sm, 10);
	pio_sm_set_enabled(pio, sm, true);
}

#endif
