// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------------- //
// gamecube_reader //
// --------------- //

#define gamecube_reader_wrap_target 0
#define gamecube_reader_wrap 17

#define gamecube_reader_T1 4
#define gamecube_reader_T2 12

static const uint16_t gamecube_reader_program_instructions[] = {
	//     .wrap_target
0x209c,
	//  0: wait   1 gpio, 28                 
0xe042,
	//  1: set    y, 2                       
0xe027,
	//  2: set    x, 7                       
0x2520,
	//  3: wait   0 pin, 0               [5] 
0x4001,
	//  4: in     pins, 1                    
0x20a0,
	//  5: wait   1 pin, 0                   
0x0043,
	//  6: jmp    x--, 3                     
0x0082,
	//  7: jmp    y--, 2                     
0x2520,
	//  8: wait   0 pin, 0               [5] 
0x20a0,
	//  9: wait   1 pin, 0                   
0xe047,
	// 10: set    y, 7                       
0xe027,
	// 11: set    x, 7                       
0x2520,
	// 12: wait   0 pin, 0               [5] 
0x4001,
	// 13: in     pins, 1                    
0x20a0,
	// 14: wait   1 pin, 0                   
0x004c,
	// 15: jmp    x--, 12                    
0x008b,
	// 16: jmp    y--, 11                    
0xb942,
	// 17: nop                           [25]
        //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program gamecube_reader_program = {
	.instructions = gamecube_reader_program_instructions,
	.length = 18,
	.origin = -1,
};

static inline pio_sm_config gamecube_reader_program_get_default_config(uint offset) {
	pio_sm_config c = pio_get_default_sm_config();
	sm_config_set_wrap(&c, offset + gamecube_reader_wrap_target, offset + gamecube_reader_wrap);
	return c;
}

#include "hardware/clocks.h"
#include "hardware/pio.h"
static inline void gamecube_reader_program_init(PIO pio, uint sm, uint offset)  
{
	pio_sm_config c = gamecube_reader_program_get_default_config(offset);
	sm_config_set_in_pins(&c, 3);
	pio_sm_set_pindirs_with_mask(pio, sm, ~(1u << 3), 1u << 3);
	pio_gpio_init(pio, 3);
	sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_RX);
	sm_config_set_in_shift(&c, false, true, 8);
	int cyclesPerBit = (gamecube_reader_T1 + gamecube_reader_T2) / 4;
	float frequency = 1000000;
	float clockDiv = clock_get_hz(clk_sys) / (cyclesPerBit * frequency);
	sm_config_set_clkdiv(&c, clockDiv);
	pio_sm_init(pio, sm, offset, &c);
	pio_sm_set_enabled(pio, sm, true);
}
static inline char gamecube_reader_getc(PIO pio, uint sm) 
{
	return pio_sm_get_blocking(pio, sm);
} 

#endif
