// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------------------- //
// gamecube_poll_reader //
// -------------------- //

#define gamecube_poll_reader_wrap_target 0
#define gamecube_poll_reader_wrap 23

#define gamecube_poll_reader_T1 4
#define gamecube_poll_reader_T2 12

static const uint16_t gamecube_poll_reader_program_instructions[] = {
	//     .wrap_target
0x209c,
	//  0: wait   1 gpio, 28                 
0xe027,
	//  1: set    x, 7                       
0x2520,
	//  2: wait   0 pin, 0               [5] 
0x4001,
	//  3: in     pins, 1                    
0x20a0,
	//  4: wait   1 pin, 0                   
0x0042,
	//  5: jmp    x--, 2                     
0x2520,
	//  6: wait   0 pin, 0               [5] 
0x20a0,
	//  7: wait   1 pin, 0                   
0xe041,
	//  8: set    y, 1                       
0xe027,
	//  9: set    x, 7                       
0x2520,
	// 10: wait   0 pin, 0               [5] 
0x4001,
	// 11: in     pins, 1                    
0x20a0,
	// 12: wait   1 pin, 0                   
0x004a,
	// 13: jmp    x--, 10                    
0x0089,
	// 14: jmp    y--, 9                     
0x8020,
	// 15: push   block                      
0xe047,
	// 16: set    y, 7                       
0xe027,
	// 17: set    x, 7                       
0x2520,
	// 18: wait   0 pin, 0               [5] 
0x4001,
	// 19: in     pins, 1                    
0x20a0,
	// 20: wait   1 pin, 0                   
0x0052,
	// 21: jmp    x--, 18                    
0x0091,
	// 22: jmp    y--, 17                    
0x8020,
	// 23: push   block                      
        //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program gamecube_poll_reader_program = {
	.instructions = gamecube_poll_reader_program_instructions,
	.length = 24,
	.origin = -1,
};

static inline pio_sm_config gamecube_poll_reader_program_get_default_config(uint offset) {
	pio_sm_config c = pio_get_default_sm_config();
	sm_config_set_wrap(&c, offset + gamecube_poll_reader_wrap_target, offset + gamecube_poll_reader_wrap);
	return c;
}

#include "hardware/clocks.h"
#include "hardware/pio.h"
static inline void gamecube_poll_reader_program_init(PIO pio, uint sm, uint offset)  
{
	pio_sm_config c = gamecube_poll_reader_program_get_default_config(offset);
	sm_config_set_in_pins(&c, 3);
	pio_sm_set_pindirs_with_mask(pio, sm, ~(1u << 3), 1u << 3);
	pio_gpio_init(pio, 3);
	sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_RX);
	sm_config_set_in_shift(&c, false, true, 32);
	int cyclesPerBit = (gamecube_poll_reader_T1 + gamecube_poll_reader_T2) / 4;
	float frequency = 1000000;
	float clockDiv = clock_get_hz(clk_sys) / (cyclesPerBit * frequency);
	sm_config_set_clkdiv(&c, clockDiv);
	pio_sm_init(pio, sm, offset, &c);
	//pio_sm_set_enabled(pio, sm, true);
}

#endif
